---
abstract: 'Read/write Brotli buffers/streams'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1002, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO-Compress-Brotli
no_index:
  directory:
    - t
    - inc
requires:
  File::Slurper: '0'
  Getopt::Long: '0'
  Time::HiRes: '0'
  perl: '5.014000'
resources:
  repository: https://git.ieval.ro/?p=io-compress-brotli.git
version: '0.004001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
